# Generated by Django 3.2.7 on 2021-11-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
