# Generated by Django 3.2.7 on 2021-11-25 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_employee_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialusers',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.account'),
        ),
    ]
