# Generated by Django 3.2.7 on 2021-11-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_specialusers_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.filial'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.status'),
        ),
    ]
