# Generated by Django 3.2.7 on 2021-11-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211125_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
