# Generated by Django 3.2.7 on 2021-11-29 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_account_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account',
            field=models.ManyToManyField(blank=True, to='users.Account'),
        ),
    ]
